### ISSUE TITLE
container.addHook is not a function

### ISSUE THREAD

**Issue by skyw4rp** [superRaytin/paginationjs#10]
i dont know why i get this error

it's happening on this part of the demo script

```
  container.addHook('beforeInit', function(){
                window.console && console.log('beforeInit...');
            });
            container.pagination(options);

            container.addHook('beforePageOnClick', function(){
                window.console && console.log('beforePageOnClick...');
                //return false
            });

            return container;
```

any ideas?

**Comment by skyw4rp** [comment]
also tried the "Quick Start"

`
$('#pagination-container').pagination({
    dataSource: [1, 2, 3, 4, 5, 6, 7, 8],
    callback: function(data, pagination) {
        // template method of yourself
        var html = template(data);
        $('#data-container').html(html);
    }
})
`

and i got 

TypeError: $(...).pagination is not a function
dataSource: [1, 2, 3, 4, 5, 6, 7, 8],

**Comment by superRaytin** [comment]
hmm..it seems you are using the plugin method before jQuery loaded.

**Comment by Ragnarok99** [comment]
I have the same error TypeError: $(...).pagination is not a function

**Comment by skyw4rp** [comment]
i have found the error, if you declare too many libraries, it will get you
that error.

try to write the function on the line where you need to use it instead of
doing it on the <head> tag or at the bottom of the page.

that worked for me.
