### ISSUE TITLE
Filtering Paginate

### ISSUE THREAD

**Issue by keuteixeira** [superRaytin/paginationjs#101]
Hi,

My website test is: https://www.nossatrip.com.br/destino-certo/oceania

I have a parent pagination that has two filter fields. These values are loaded from a constant in the "result_json" code.
By clicking on one of these results there is a second pagination that has a filter and an ordering.
I would like to know how I can modify my code so that if I modify one of those fields it will filter or sort without having to perform another query in the database for example.

**Comment by muhdammar** [comment]
hi do you know how to filter and redrawing the pagination content?
