### ISSUE TITLE
How can I center Pagin UI?

### ISSUE THREAD

**Issue by cwoo3511** [superRaytin/paginationjs#104]
Hi,

How can I center it?
'text-aline: center' was not valid.

**Comment by benmcm1994** [comment]
You spelt text-align wrong mate.

**Comment by cwoo3511** [comment]
> You spelt text-align wrong mate.

You are right, but it is not valid either.
I want the whole UI to be center aligned

**Comment by yuhsiang237** [comment]
> Hi,
> 
> How can I center it?
> 'text-aline: center' was not valid.

You can try this to centered pagin UI
```
<div class="text-center">
     <div id="pagination" class="d-inline-block">
     </div>
</div>
```
It's work👌
