### ISSUE TITLE
Update pagination data source?

### ISSUE THREAD

**Issue by benmcm1994** [superRaytin/paginationjs#107]
Is it possible to update the current array of the paginated content? I'm trying to sort the array of my paginated content via a button. So I would sort the array and then repopulate the paginationjs.

Redrawing the whole pagination would work or just replacing it all together, but how would I do this? 

Would appreciate help! Thanks.

**Comment by muhdammar** [comment]
i have try to sort the json data like the example, seems their have bugs when using json data, however, if i test with simple array of integer. it works like charm

**Comment by muhdammar** [comment]
```
function init() {
					$('#pagination-container').pagination({
						dataSource: '/events/event/paging/card',
						locator: 'data',
						totalNumberLocator: function (response) {
							return response.recordsTotal;
						},
						pageNumber: 1,
						pageSize: 6,
						ajax: {
							beforeSend: function () {
								$('#data-container').html('Loading data from server...');
							},
							data: {
								//Use for filter event
								extraParams1: $('#Id').val(),
								extraParams2: $('#TenantId').val(),
								extraParams3: $('#StartTime').val(),
								extraParams4: $('#EndTime').val(),
							}
						},
						callback: function (data, pagination) {
							var template = Handlebars.compile($('#template-demo').html());
							var source = data;
							var html = template(source);
							$('#data-container').html(html);
						}
                    });
                console.log("init");
				}

            init();
```

U can call init on any filter button click or etc

**Comment by benmcm1994** [comment]
> 
> 
> ```
> function init() {
> 					$('#pagination-container').pagination({
> 						dataSource: '/events/event/paging/card',
> 						locator: 'data',
> 						totalNumberLocator: function (response) {
> 							return response.recordsTotal;
> 						},
> 						pageNumber: 1,
> 						pageSize: 6,
> 						ajax: {
> 							beforeSend: function () {
> 								$('#data-container').html('Loading data from server...');
> 							},
> 							data: {
> 								//Use for filter event
> 								extraParams1: $('#Id').val(),
> 								extraParams2: $('#TenantId').val(),
> 								extraParams3: $('#StartTime').val(),
> 								extraParams4: $('#EndTime').val(),
> 							}
> 						},
> 						callback: function (data, pagination) {
> 							var template = Handlebars.compile($('#template-demo').html());
> 							var source = data;
> 							var html = template(source);
> 							$('#data-container').html(html);
> 						}
>                     });
>                 console.log("init");
> 				}
> 
>             init();
> ```
> 
> U can call init on any filter button click or etc

Literally just initialise the pagination everytime to update the data?

**Comment by muhdammar** [comment]
yes everytime u click the update button for example, just call it again inside onclick function, do you get what i mean?
