### ISSUE TITLE
paginationData is undefined

### ISSUE THREAD

**Issue by devrow** [superRaytin/paginationjs#11]
jquery-1.12.3
paginationjs-2.0.7

```
$('#paginator').pagination({
    dataSource: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    pageSize: 2,
    autoHidePrevious: true,
    autoHideNext: true,
    callback: function(data, pagination) { }
});
```

TypeError: paginationData is undefined js/pagination-2.0.7/pagination.js Line 656

**Comment by superRaytin** [comment]
Here is a demo which using the code you gave above, and it works well:

http://codepen.io/superRaytin/pen/RRoZBz?editors=0010

I need more info.

**Comment by 0xAli** [comment]
This happened to me as well, i was just stupid and neglected to actually add the #paginator div.

**Comment by jmediatechnology** [comment]
I had the same problem. It was caused because 

`<div id="pagination-container"></div>`

was not existing on the webpage. I had the div in a template file, and that template was not properly included.
