### ISSUE TITLE
How to render table on specific page/item?

### ISSUE THREAD

**Issue by galih56** [superRaytin/paginationjs#113]
I'm currently working on a sortable table. I combined pagination.js and sortable from jquery-ui. My problem is if i sort some items on a specific page. after i do that. pagination will always render and focus on the first page. I want to render the table on specific page/item. Is it possible? Maybe getting selected page number can help

**Comment by superRaytin** [comment]
try resetPageNumberOnInit https://pagination.js.org/docs/index.html#resetPageNumberOnInit
