### ISSUE TITLE
return extra data when using ajax request?

### ISSUE THREAD

**Issue by morrow95** [superRaytin/paginationjs#116]
Using the example given in the docs... response is expected to be an array of results.  Is there any way to return additional data along with this (not part of the result set) so that it can be accessed in the `callback: function(data, pagination)`?  Preferably I would like to do something like data.results is my result set then have access to data.extra in the callback with my additional data.

```
     dataSource: function(done) {
        $.ajax({
            type: 'GET',
            url: '/test.json',
            success: function(response) {
                done(response);
            }
        });
     }
```

**Comment by superRaytin** [comment]
i think you can do this completely outside of Pagination

**Comment by pdw-mb** [comment]
I've hit this problem, and I don't see how this is possible outside of Pagination without making a separate ajax call.

Here's the response data I want to process:

```json
{
   "data": [ ],
   "included": { }
}
```

The items are in `data`, but I also need access to information in `included`.  

This arrangement of data is specified by the [jsonapi](https://jsonapi.org/) spec.

The callback function can only get an array as input (either directly, or by specifying a locator).  It seems like `formatResult` would be the right place to do some pre-processing, but that also only gets passed the array resulting from applying the locator, so no way to get at `included`.

The only solution I've found is to use `ajaxFunction` to provide a wrapper for `$.ajax` that pre-processes the returned data.

**Comment by superRaytin** [comment]
@pdw-mb I've noticed this, I added a `originalResponse ` property to the callback's `pagination` parameter object, now you can access the original response of the request sent by each paging when `dataSource` is an URL. Just upgrade to `2.5.0` 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/2723376/209103308-ea9c0593-ca1e-47fe-91ad-300203ffb235.png">

In your case:

```js
$('#demo').pagination({
    dataSource: '/data.json',
    callback: function(data, pagination) {
        // pagination.originalResponse.included
        var html = template(data);
        dataContainer.html(html);
    }
})
```

**Comment by pdw-mb** [comment]
Ah - perfect, thank you!  I somehow missed `originalResponse` when looking at the documentation.

I've raised https://github.com/superRaytin/paginationjs/pull/137 to help make this a bit more obvious.
