### ISSUE TITLE
Cannot format pageNumber

### ISSUE THREAD

**Issue by NayabHussain** [superRaytin/paginationjs#118]
**Describe the bug**
Cannot format pageNumber

**Expected behavior**
want to format pageNumber like   << -< - 1/4 - > - >>

**Versions:**
 - Pagination: [e.g. 2.1.5]
 - jQuery [e.g. 1.8.3]
 - Browser [e.g. Chrome]

**Additional context**

**Comment by superRaytin** [comment]
this is not currently supported
