### ISSUE TITLE
Discover typo in pagination.css

### ISSUE THREAD

**Issue by hannapa1114** [superRaytin/paginationjs#121]
**Describe the bug**
I found typo in pagination.css 
line number is 284
```
.paginationjs .paginationjs-pages li.paginationjs-next {
  border-right: 1px solid #aaa/9;
}
```

**To Reproduce**
Provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz
```
.paginationjs .paginationjs-pages li.paginationjs-next {
  border-right: 1px solid #aaa;
}
```

**Expected behavior**

**Versions:**
 - Pagination: [e.g. 2.1.5]
 - jQuery [e.g. 1.8.3]
 - Browser [e.g. Chrome]

**Additional context**

**Comment by superRaytin** [comment]
It is not a typo, `\9` is a "CSS hack" specific to Internet Explorer 7, 8, & 9.
