### ISSUE TITLE
Pagesize attribute not working with Asynchronous http get request

### ISSUE THREAD

**Issue by BombeyR-zz** [superRaytin/paginationjs#122]
**Description of the Issue**
When I use asynchronous request to Flickr, the pagination container produces the complete list irrespective of the pageSize attribute

**To Reproduce**
https://codepen.io/bombeyr/pen/Jjbvdjv

**Expected behavior**
When I set pageSize to 12, I need the pagination container to contain a maximum of 12 items

**Versions:**
 - Pagination: [e.g. 2.1.5]
 - jQuery [e.g. 1.8.3]
 - Browser [e.g. Chrome]

**Additional context**

**Comment by superRaytin** [comment]
Pagination will not process the data items of the asynchronous request, what it does is pass all the data returned from the request to the `callback` function
