### ISSUE TITLE
Strange URL param appears

### ISSUE THREAD

**Issue by ZeroCoolHacker** [superRaytin/paginationjs#124]
**Describe the bug**
the datasource url is giving me a wierd variable in it as underscore (_)
http://localhost:8000/business/prefund-requests/2fe0c1cf-4847-4bea-b2f9-4324635edecd?order=ASC&size=1&page=1&_=1615547375208

**To Reproduce**
```
$(document).ready(function() {
            $('#pagination-container').pagination({
                dataSource: 'http://localhost:8000/business/prefund-requests/2fe0c1cf-4847-4bea-b2f9-4324635edecd?order=ASC',
                locator: 'result.prefundList',
                totalNumberLocator: function (response) {console.log(response);return 1;},
                pageNumber: 1,
                pageSize: 1,
                alias: {
                    pageNumber: 'page',
                    pageSize: 'size'
                },
                ajax: {
                    type: 'GET',
                    dataType: 'json',
                },
                callback: function(data, pagination) {
                    // template method of yourself
                    showDataInTablePaginationLib(data);
                }
            })
        })
```
**Expected behavior**
The request should be sent to http://localhost:8000/business/prefund-requests/2fe0c1cf-4847-4bea-b2f9-4324635edecd?order=ASC&size=1&page=1

**Versions:**
 - Pagination: [ 2.1.5]
 - jQuery [3.6.0]
 - Browser [FireFox]

**Additional context**

**Comment by superRaytin** [comment]
Do you mean there is an extra `_=1615547375208` on the link?

I'm sure that is not Pagination does
