### ISSUE TITLE
异步分页的totalNumber值

### ISSUE THREAD

**Issue by ziyoung** [superRaytin/paginationjs#13]
异步分页时的totalNumber该如何设置？查阅文档，未找到答案。

**Comment by superRaytin** [comment]
#5

**Comment by LukerSpringtree** [comment]
作者你好, 我也感觉到这个  异步分页的  totalNumber 好难处理

好像只能写死一样!

如何动态设置 其值!

**Comment by superRaytin** [comment]
@LukerSpringtree 参考这里 https://github.com/superRaytin/paginationjs/issues/2#issuecomment-99113835
