### ISSUE TITLE
Cannot read properties of undefined (reading 'hooks')

### ISSUE THREAD

**Issue by dedelgado** [superRaytin/paginationjs#131]
**Describe the bug**
The following error happens to me, when I reload the page and stay on that page everything loads fine, but if I reload the page and change the browser tab, it does not load the pagination and that error appears
![image](https://user-images.githubusercontent.com/89319487/183091270-fcdfd4fe-fe61-4ac8-9adf-22902fa70772.png)

**To Reproduce**
Provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Expected behavior**
It is expected that when you reload the page and change the page, it will continue to reload and that the error will not appear

**Versions:**
 - Pagination:  2.1.5
 - Browser  Chrome - Firefox -etc

**Comment by hyunzxn** [comment]
I have exactly same issue. Did you solve this issue?
