### ISSUE TITLE
How do i asynchronous in post request.

### ISSUE THREAD

**Issue by sforest1975** [superRaytin/paginationjs#132]
I want to send POST request in asynchronous mode.
data should retrive each page when click pagination.

totalNumber should send by the server.
but, totalNumber is only accept dataSource is URL.
but, URL mode is only GET.
If I want to send POST, must write by function

`$(...').pagination({`
`  dataSource: (done) => {`
`    return done($.post(`
`      'http://www.com/getpage/1', // retrive data only one page.`
`      $(form).serialize());`
`  },`
`  totalNumber: () => {`
`    return $.post(`
`      'http://www.com/getTotal', // retrive total number of result.`
`      $(form).serialize());`
`  },`
`  callback: (d, p) {`
`    ... // display process`
`  }`
`});`

I am not sure difference between 'totalNumber' and 'totalNumberLocator'.

simple imagination sample code.
`$('...').pagination({`
`  dataSource: (done) => { // <- if use POST must written by function().`
`     return done([1, 2]); // sample.  POST returns [1,2]. total records count is 100.`
`  },`
`  totalNumber: 100, // <- if i use dataSource in function, 100 is ignored.`
`  totalNumberLoator: 100, // <- this ignore too.`
`  callback: (d, p) {`
`    ... // display process`
`  }`
`});`

if i want to send totalNumber, should dataSource in URL.
but, cannot send POST by URL.

`$('...').pagination({`
`  dataSource: 'http://xxx.com/yyy/', <- I cannot send POST by URL.`
`  totalNumber: 100, // <- totalNumber works.`
`  callback: (d, p) {`
`    ... // display process`
`  }`
`});`

I have no idea to send POST request in asynchrounous mode.
I cannot send total data to browser, because too much data.

**Comment by superRaytin** [comment]
I believe `ajax` param is what you want: https://pagination.js.org/docs/index.html#ajax

`totalNumberLocator` is used to retrive total size from the response of remote request, below is an example:

Assume that your response's structrue is:

```js
{
  success: true,
  results: {
    list: [{...}],
    totalNumber: 100,
  }
}
```

Then you can invoke pagination like this:

```js
$('#container').pagination({
    dataSource: 'http://www.com/getpage',
    locator: 'results.list',
    ajax: {
      type: 'post',
    },
    pageSize: 5,
    totalNumberLocator: 'results.totalNumber',
    callback: function(data, pagination) {
        // template method of yourself
        var html = template(data);
        dataContainer.html(html);
    }
})
```
