### ISSUE TITLE
DataSource in URL format send ajax request twice

### ISSUE THREAD

**Issue by RadikFakhriev** [superRaytin/paginationjs#135]
**Bug description**
After click to pagination controls API source calling twice.

**To Reproduce**
On the homepage of project in sections: "Asynchronous & Dynamic total number" and "Asynchronous or JSONP".
You can watch to Network Monitor or Console of browser, after paginating. Each click call api twice.

**Expected behavior**
Each click call api once

**Versions:**
 - Pagination: 2.4.1
 - jQuery 3.5.1
 - Browser Chrome 108.0.5359.73

**Comment by superRaytin** [comment]
Thanks for the feedback, pls upgrade to `2.4.2`
