### ISSUE TITLE
`display: flex;` makes the pagination not centered

### ISSUE THREAD

**Issue by njzjz** [superRaytin/paginationjs#138]
**Describe the bug**
#133 introduces `display: flex;` which makes my page's pagination no longer centered.

![image](https://user-images.githubusercontent.com/9496702/210765539-89eb0779-53fa-49c4-8f58-d76ce2f7ed69.png)

**To Reproduce**
without `display: flex`: [here](https://a0b21b23.reacnetgenerator.pages.dev/report?jdata=https%3A%2F%2Fgist.githubusercontent.com%2Fnjzjz%2Fe9a4b42ceb7d2c3c7ada189f38708bf3%2Fraw%2F83d01b9ab1780b0ad2d1e7f934e61fa113cb0f9f%2Fmethane.json)

with `display: flex;`: [here](https://8ea02639.reacnetgenerator.pages.dev/report?jdata=https%3A%2F%2Fgist.githubusercontent.com%2Fnjzjz%2Fe9a4b42ceb7d2c3c7ada189f38708bf3%2Fraw%2F83d01b9ab1780b0ad2d1e7f934e61fa113cb0f9f%2Fmethane.json)

**Expected behavior**
Without `display: flex`:

![image](https://user-images.githubusercontent.com/9496702/210765152-38df9e91-1ecc-454a-85c5-6a7ecaf25135.png)

**Versions:**
 - Pagination: 2.3.0
 - jQuery 3.6.1
 - Browser Edge

**Additional context**

My HTML code is
```html
<div class="mx-auto text-center mt-5">
  <div id=speciespager></div>
</div>
```

**Comment by njzjz** [comment]
I fix it by adding the style `display: unset`. I'd like to know if there are any suggestions.
```css
.paginationjs {
    display: unset!important;
}
```

**Comment by superRaytin** [comment]
@njzjz `justify-content` also is an option:
```css
.paginationjs {
    justify-content: center;
}
```

**Comment by njzjz** [comment]
Thanks, it looks good to me.
