### ISSUE TITLE
pageNumberStartWithZero works only once

### ISSUE THREAD

**Issue by ememisya** [superRaytin/paginationjs#139]
The configuration 
```
       ajax: {
           pageNumberStartWithZero: true,
       },
```
Only seems to work once, after which it is deleted for some reason.
https://github.com/superRaytin/paginationjs/blob/51e97b2014e271e0c403d121eaa81d533d29244d/src/pagination.js#L427

A workaround to make this compatible with [Spring](https://docs.spring.io/spring-data/rest/docs/2.6.x/reference/html/#_paging) appears to be the following:

```
const paginationConfig = {
       ajax: {
            pageNumberStartWithZero: true,
            beforeSend: function() {
                paginationConfig.ajax.pageNumberStartWithZero = true;
                dataContainer.html('Loading data from flickr.com ...');
            }
       }
}
```
Was this behaviour intentional?

**Comment by superRaytin** [comment]
Fixed, pls try `2.5.1`.
