### ISSUE TITLE
TypeError: $(...).pagination is not a function

### ISSUE THREAD

**Issue by GeyangYu** [superRaytin/paginationjs#14]
Hey, I tried to put the $(...).pagination within a function, but it will report the error: TypeError: $(...).pagination is not a function. If I put it just within the <script></script>, then it can work. I also tried the demo you give, but still get the error. Could anyone please help me? Thanks a lot.

**Comment by superRaytin** [comment]
Could you please provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Comment by GeyangYu** [comment]
`<script type="text/javascript">

    $(document).ready(function () {
        LoadItems(@Html.Raw(allItems));
    });

    LoadItems(@Html.Raw(allItems));

    function LoadItems(items) {

        $('#pagination-container').pagination({
            dataSource: items,
            pageSize: 16,
            showGoInput: true,
            showGoButton: true,
            callback: function (items, pagination) {
                LoadOnlineStoreGrid(items);
            }
        });
    };`

Thanks for the reply. In this code, if I call the LoadItems() function in the  $(document).ready(function () ), then it will report the error. If I directly call the LoadItems() in the script, then it can work. Do you know why? Thanks a lot.

**Comment by GeyangYu** [comment]
<script type="text/javascript">

    $(document).ready(function () {
        LoadItems(@Html.Raw(allItems));
    });

    LoadItems(@Html.Raw(allItems));

    function LoadItems(items) {

        $('#pagination-container').pagination({
            dataSource: items,
            pageSize: 16,
            showGoInput: true,
            showGoButton: true,
            callback: function (items, pagination) {
                LoadOnlineStoreGrid(items);
            }
        });
    };

   ...

</script>

Thanks for the reply. In this code above, if I call the function LoadItems() in the    $(document).ready(function () ), then it will report the error. But if I call the function LoadItems() directly in the script, then it can work. Do you know why? Thanks a lot.

**Comment by GeyangYu** [comment]
Thanks for the reply. I tried my code in the demo, it actually works. But just failed locally. It only works if I put the function directly within the <script></script>, but if I call the function later, it will report the error. Do you have any idea about it? Thanks a lot!

**Comment by GeyangYu** [comment]
Thanks for the reply. I tried my code in the demo, it actually works. But just failed locally. It only works if I put the function directly within the "script", but if I call the function later, it will report the error. Do you have any idea about it? Thanks a lot!

**Comment by GeyangYu** [comment]
Thanks for the reply. I just figured it out.

**Comment by neutt22** [comment]
Im still having this issue, even the codepen provided didn't work for me.

**Comment by superRaytin** [comment]
@neutt22 try again: https://codepen.io/superRaytin/pen/RRoZBz

**Comment by neutt22** [comment]
@superRaytin here you go:

![image](https://user-images.githubusercontent.com/8733987/33062522-8a004cc8-ceda-11e7-91bf-04672224e0ff.png)

**Comment by superRaytin** [comment]
@neutt22 I replaced the 'http' resources with 'https', i think it can works now.

**Comment by neutt22** [comment]
ahh yes, thanks! working now :)

**Comment by neutt22** [comment]
sadly on my local project this issue isn't still resolved:
![image](https://user-images.githubusercontent.com/8733987/33062969-ed170cec-cedb-11e7-9e89-4f9bf36bd809.png)

I copy exactly the code in the JS section

**Comment by superRaytin** [comment]
@neutt22 please show me your code, i'll reply you later

**Comment by neutt22** [comment]
Thanks!

here it is:
![image](https://user-images.githubusercontent.com/8733987/33063123-81325332-cedc-11e7-81e6-32219d478405.png)

**Comment by superRaytin** [comment]
@neutt22  uh, you should define a `template` method to render the data

**Comment by neutt22** [comment]
Will that solve the error `container.pagination is not a function`?

**Comment by superRaytin** [comment]
Did you have a git repo contains those code? I'd like to get the context information.
