### ISSUE TITLE
how to reload ajax data?

### ISSUE THREAD

**Issue by alfiansetia** [superRaytin/paginationjs#141]
**Describe the bug**

**To Reproduce**
Provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Expected behavior**

**Versions:**
 - Pagination: [e.g. 2.1.5]
 - jQuery [e.g. 1.8.3]
 - Browser [e.g. Chrome]

**Additional context**

**Comment by superRaytin** [comment]
Ref #77
