### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by liu-dongyu** [superRaytin/paginationjs#15]
想用`npm install`来下载，能否发布到npm版本库？

**Comment by superRaytin** [comment]
https://www.npmjs.com/package/paginationjs 你已经发上去了？ 😂

**Comment by liu-dongyu** [comment]
是啊 我发一个先用着。你发布的话我就删掉我那个

**Comment by liu-dongyu** [comment]
> If the version is older than 24 hours, then the unpublish will fail, with a message to contact support@npmjs.com.

版本发布超过24小时不能轻易`npm unpublish`。我已经联系 support@npmjs.com 了，说要换发布者，希望能删掉现在的版本。

**Comment by superRaytin** [comment]
谢谢，以前考虑过发到 npm，后来遗忘了，然后就没有然后了 :）

**Comment by afc163** [comment]
@liu-dongyu 给 @superRaytin 加上 owner 权限就行了。

**Comment by superRaytin** [comment]
嗯，给我 owner 权限 @liu-dongyu

**Comment by liu-dongyu** [comment]
应该可以了。
