### ISSUE TITLE
Add first and last pagination links

### ISSUE THREAD

**Issue by mandaliya** [superRaytin/paginationjs#17]
Is it possible to add first and last page links in pagination?

**Comment by superRaytin** [comment]
Nope, it sounds weird... could you tell me why you want to do this?

**Comment by guoxiangwen** [comment]
hello guy, if i want to genarate page info from api which like [totalElement:123,totalPage:13,content:.....] ,but in your case,the dataSource param can not do this

**Comment by guoxiangwen** [comment]
when ajax url datasourse, how can i know the totalNumber? the totalNumber is return by the url

**Comment by superRaytin** [comment]
@guoxiangwen trace on: #3 #2

**Comment by mandaliya** [comment]
I wanted to add two more buttons in pagination. One for first page and second for last page. Is it possible.?

But, I realized that first page and last page is always visible, so there is no need for this.
