### ISSUE TITLE
想请教为什么一次性请求所有的数据回来呢？

### ISSUE THREAD

**Issue by herrdu** [superRaytin/paginationjs#23]
datasource 加载的是所有的数据，这样当数据量超过大（超过10W条），是不是加载会变慢？
为什么不采用每次点击请求一次数据的方法呢？

**Comment by allenfantasy** [comment]
@herrdu 用 [`ajax`](http://paginationjs.com/docs/index.html#ajax) 这个选项来进行每页请求。

**Comment by superRaytin** [comment]
如果想要异步分页，可以指定 dataSource 为数据 URL 如 `/data.json`，查看文档：http://paginationjs.com/docs/index-cn.html#dataSource
