### ISSUE TITLE
关于动态加载totalNubmer

### ISSUE THREAD

**Issue by LukerSpringtree** [superRaytin/paginationjs#32]
你好!
感觉好像  option 对象的 totalNumber 只能写死吗?

totalPage 倒是 可以在 callback里面设置 但是  totalNumber只能在 callback 外面设置 这样当内容偏少的时候,总感觉不好处理

反正我处理得挺纠结的
可能是我太菜了吧.

麻烦,请问有没有解决的办法

            var options = {
	            dataSource:  'http://192.168.1.200:9009/ApiHome/GetApiNewsList',
	            locator: function () {
	            	return 'Data'
	            },
	            callback: function (response, pagination) {
                    window.console && console.log(response, pagination);
		            pagination.totalPage = 8;

                    var dataHtml = '<ul>';

                    $.each(response, function (index, item) {
                    	var year = item.PublishDate.slice(0,4);
                    	var mouth = item.PublishDate.slice(5,7);
                    	var day = item.PublishDate.slice(8,10);
                        dataHtml += "<li class='myli'><a href='#'><div class='item'><p>"+ day +"</p><span>" + year +"/"+ mouth +"</span></div><p>" +  item.Title + "</p></a></li>";
                    });

                    dataHtml += '</ul>';

                    container.prev().html(dataHtml);
                },
	            totalPage:10,
	            totalNumber: 80,
	            pageSize: 8,
                showGoInput: true,
                showGoButton: true,
                prevText: "上一页",
                nextText: "下一页",
                goButtonText: "确认",
                formatGoInput: '共<%= totalPage %>页 跳转到 <%= input %> 页',
	            alias: {
		            pageNumber: 'page',
		            pageSize: 'psize'
	            }
            };

我这样设置option的话. 开始加载时  80/8 10 页.callback外面的 totalpage:读取不了.

当我点击一个页码按钮的时候   总页数变为8. 感觉很突兀. 在里面倒是可以改变totaPage

好纠结

**Comment by LukerSpringtree** [comment]
我的想法是 能不能 初始化的时候,就动态设置 totalNumber的值

我尝试过.先写一个 ajax 来获取totalNumber 再 赋值 给ta但是可能由于 异步加载的原因 都没法获取

估计要用  es6的  promise 

好吧.

**Comment by LukerSpringtree** [comment]
好吧 我学习了下  promise  好像解决了.谢谢!

**Comment by superRaytin** [comment]
#2
