### ISSUE TITLE
Unknown total number before request?

### ISSUE THREAD

**Issue by lordplagus02** [superRaytin/paginationjs#34]
I know that this has been addressed in several issues, but I cannot read the commentary as it is all in presumably Mandarin 😢. So I'm going to open this issue again but in English...

So when loading content asynchronously from a remote data source, the docs say you should specify the total number of items in the pagination object as `totalNumber`, before actually knowing what the total number is. When we request remote data we cannot know how many items are in the full list before the request is completed. My API is designed to return the total number of objects in the unpaginated list and total number of pages, but I cannot make use of this data?

Again, apologies for reopening this but I really need some clarity in English. Thank you!

**Comment by superRaytin** [comment]
please upgrade to `2.1.0` 

ref: https://github.com/superRaytin/paginationjs/issues/2#issuecomment-341108813
