### ISSUE TITLE
Update jquery to ~2.2.0

### ISSUE THREAD

**Issue by ugoa** [superRaytin/paginationjs#4]
Hi, quite nice pagination library, good work.
Just wondering if you can update the jquery dependency so that it can be compatible with latest version (~2.2.0 I believe), thanks a lot!
你好，很好的分页插件， 👍 。
就是可不可以把 jQuery 的依赖升级成兼容最新版本，我下载了之后和我其他的插件有依赖有冲突，不想保持好几个 jQuery 版本。多谢了。

**Comment by superRaytin** [comment]
感谢反馈，我会抽时间做一个兼容测试，或许明天？同样也欢迎 PR。

**Comment by superRaytin** [comment]
在 1.7.x 和 2.2.x 上测试过了，都是可以正常使用的，见 Demo: 

http://codepen.io/superRaytin/pen/ezOyqM

如果有兼容问题，麻烦提供浏览器的报错信息，或其他有价值的信息，方便我进行排查 😄
