### ISSUE TITLE
Allow customizing the names of request parameters for asynchronous requests

### ISSUE THREAD

**Issue by manish-in-java** [superRaytin/paginationjs#41]
Asynchronous requests include the parameter names `pageNumber` and `pageSize`. Options such as `pageNumberParameterName` and `pageSizeParameterName` would allow customizing these since some backends may already be expecting parameters with certain names.

**Comment by manish-in-java** [comment]
I see that there is an undocumented `alias` configuration parameter that allows customizing parameter names as:

    $(selector).pagination({ alias : { pageNumber : "page", pageSize : "rows" } });

This is sufficient for what I am looking for. It will be useful to have this documented so that users can find this easily.

**Comment by superRaytin** [comment]
I guess you have not seen this document: http://pagination.js.org/docs/index.html#alias
