### ISSUE TITLE
Allow customizing the titles for the previous and next buttons

### ISSUE THREAD

**Issue by manish-in-java** [superRaytin/paginationjs#42]
The previous button has the hard-coded title `Previous page` and the next button similarly has the hard-coded title `Next page`. There titles should be customizable so that localized text can be used.

**Comment by superRaytin** [comment]
Guess what you want is http://pagination.js.org/docs/index.html#prevText and http://pagination.js.org/docs/index.html#nextText

**Comment by typo3ua** [comment]
@superRaytin its is not that...

in your JS i see...
```
<li class="' + classPrefix + '-prev J-paginationjs-previous" data-num="' + (currentPage - 1) + '" title="Previous page">
<a href="' + pageLink + '">' + prevText + '<\/a>
<\/li>'
```
So, as you see, I can change this `>' + prevText + '<`  but i can not change this ` title="Previous page">`

The question how can i change this text  ` title="Previous page">`???
