### ISSUE TITLE
callback if no data

### ISSUE THREAD

**Issue by agusesetiyono** [superRaytin/paginationjs#49]
how to return in callback when no data available?

`uncaught Error: Pagination: dataSource.data is undefined`

**Comment by superRaytin** [comment]
Could you please provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Comment by AceLynn** [comment]
是不是类似这样的场景？我现在也遇到了，比如： https://codepen.io/Acelynn/pen/OwGxva 
当ajax返回这样的结果的时候，{"status":0, "msg": "nothing data!"}，就是提示类似dataSource.data或者dataSource.xxx不存在的情况。现在是先用ajax请求，返回有数据的才执行分页插件，比如：
$.ajax({
url: api,
xxx
success: function(res) {
 if(res.status == 'success') {
 // pagination here
paginationFun();
 }
}
});
这样写，数据是可以正常，但是分页没用。显示出来的分页只有1页，点前后翻页页没用。
如果在paginationFun()里面重新进行一次数据请求，分页就正常。但是这样加载和刷新都会导致2次的ajax请求。有办法处理么？
问题总结：
1、如果dataSource通过ajax获取，返回的数据格式ok的时候，分页没问题；但返回的数据格式不对的时候，有没有其他方式可以避免继续操作分页插件（而不是报错）？
2、在ajax请求成功后的success里面运行分页插件会有bug吗？貌似无法正确分页，还没发现问题的症结在哪里。

**Comment by superRaytin** [comment]
@AceLynn @agusesetiyono `locator` can solve your problems, doc: http://pagination.js.org/docs/index.html#locator
