### ISSUE TITLE
ajax异步获取，怎么设置total呢

### ISSUE THREAD

**Issue by docikaci** [superRaytin/paginationjs#5]
我看total 都是预定义的？还有自定义的一些参数怎么每次都带上呢？多谢

**Comment by docikaci** [comment]
数据大概是这样：
![image](https://cloud.githubusercontent.com/assets/7788102/15563405/ec653722-233a-11e6-9ee7-407492243272.png)

**Comment by superRaytin** [comment]
Trace: #2 #3

**Comment by superRaytin** [comment]
自定义参数可以在 dataSource 中指定，比如 url 的形式：`/data.json?param=abc`

http://paginationjs.com/docs/index-cn.html#dataSource
