### ISSUE TITLE
Bower old jQuery version dependency

### ISSUE THREAD

**Issue by edmundo096** [superRaytin/paginationjs#50]
The project lists as dependency:
```
   "dependencies": {
        "jquery": "git://github.com/components/jquery.git#~1.8.3"
    }
```
What versions of jQuery does the library supports?
Could it support a newer version of jQuery?
If so, could the version be changed to something like ` "jquery": ">=1.8.3"` or so on bower?

I don't see any jQuery dependency in npm's `package.json`, so this dependency could be changed to be more flexible, or even removed.

Anyways, thanks for the plugin.

**Comment by superRaytin** [comment]
Yeah, i think it works fine with newer jQuery version
