### ISSUE TITLE
Add demo example working with server side

### ISSUE THREAD

**Issue by manueljordan** [superRaytin/paginationjs#58]
Is possible add an example about a variation of the current example but retrieving the data from the server side? It for a more realistic scenario.

Thank you

**Comment by fabiofdsantos** [comment]
@manueljordan,

Do you want a RESTful/SOAP/Whatever HTTP API example? It really depends on the programming language you are using on the server-side.

**Comment by manueljordan** [comment]
Hello, @fabiofdsantos 

I work with Java and Spring Framework. For the latter, something with Ajax. Working with Spring MVC `@Controller`. Returning 'raw' data.

**Comment by MR-AMDEV** [comment]
A PHP example would be great also .Thanks

**Comment by superRaytin** [comment]
sorry, i can't help for this, can someone help?
