### ISSUE TITLE
關於呼叫問題

### ISSUE THREAD

**Issue by RexChip** [superRaytin/paginationjs#6]
問題可能會問題太愚蠢，還請見諒。在此先謝謝您的回答。

```
<div id="wrapper">
    <header>
        <h1>Email Address Extractor</h1>
    </header>
    <form id="input">
        <input type="text" name="email" />
        <button id="convert" type="button" onclick="Normalizer.align($('#input > input').val());">Convert</button>
    </form>
    <div id="result" onmouseover="Normalizer.showReport(this,$('table#records tr:first-child'));"></div>
    <div class="end-of-float"></div>
    <table id="records">
        <thead>
            <tr>
                <th class="long-cell">Input</th>
                <th class="long-cell">E-Mail</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3" style="padding:10px;">
                    <button type="button" onclick="Normalizer.clear();">Clear all history</button>
                </td>
                <td>
                    <div id="test-pag" class="quotes">test</div>
                </td>
            </tr>
        </tfoot>
        <tbody></tbody>
    </table>
    <footer>
    </footer>
</div>
```

我使用的是 jquery-2.1.1.min.js 這個版本的 jquery，
然後這段 code 是要把不正確的 email 格式轉換成，正確的格式，
例如：1_test code at gmail com    >    1_testcode@gmail.com
這一段換顯示在 records 裡的 tbody 的 tr，tr 是當第一次轉換 email 的時候會建立的。

我試著把看到的範例帶進去

```
window.onload = function() {
    $('table#records tfoot test').pagination({
        dataSource: [ {a: 1}, {a: 2}, {a: 3}, {a: 4}, {a: 5}, {a: 6}, {a: 7}, {a: 8}, {a: 9}, {a: 10} ],
        pageSize: 5,
        formatResult: function(data) {
            for (var i = 0, len = data.length; i < len; i++) {
                data[i].a = data[i].a + $('table#records tbody tr');
            }
        },
        callback: function(data, pagination) {
            // template method of yourself
            var html = template(data);
            dataContainer.html(html);
        }
    })
}
```

這樣去測試會得到 pagination.js:656 Uncaught TypeError: Cannot read property 'hooks' of undefined，這樣的錯誤訊息，關於 addhook 的方法，我嘗試了好幾次，也不知道該怎麼使用，在這之中我也不確定我的方法是否正確，我花了一個月的時間在解決這個，因為想學習更多的 code 卻一直卡在這裡讓我非常的無助... 在此先謝謝您的回答。

**Comment by superRaytin** [comment]
我写了一个简单的示例，可以参考一下：http://codepen.io/superRaytin/pen/VjZNJN?editors=0010

**Comment by superRaytin** [comment]
另外，你的代码存在一些比较明显的问题，比如：
1. 页面要使用 `div + css` 来布局
2. JS 代码避免写在 HTML 里面

建议你进一步学习 Javascript 基础，掌握 jQuery 的一些基本用法，同时加强代码书写规范的学习。

**Comment by RexChip** [comment]
好的，關於第二部份 JS 代碼我有寫在另外一個 JS 檔，謝謝您的建議。

**Comment by superRaytin** [comment]
第二点，其实我的意思是，逻辑与结构分离，比如这一句：

```
<button type="button" onclick="Normalizer.clear();">Clear all history</button>
```

可以修改为这样写：

HTML:

``` html
<button type="button" id="J-clear-history">Clear all history</button>
```

JS:

``` js
$('#J-clear-history').on('click', function() {
  Normalizer.clear();
});
```

**Comment by RexChip** [comment]
好的，我懂您的意思了，謝謝您的建議！

**Comment by RexChip** [comment]
您好，我嘗試了幾天之後我還是不太能理解，當我把 template 的 li 改成 tr 的時候，就會無法顯示，那這樣代表的是我要另外把 $('#records tbody tr') 放在別的地方嗎？在此先謝謝您的回答

**Comment by RexChip** [comment]
Leon Shi 您好，因為您關閉了問題我不確定你會不會看到，所以使用寄信的方式，請見諒。
我嘗試了幾天之後我還是不太能理解，當我把 template 的 li 改成 tr 的時候，就會無法顯示，那這樣代表的是我要另外把
$('#records tbody tr') 放在別的地方嗎？在此先謝謝您的回答。

2016-05-29 0:29 GMT+08:00 Leon Shi <notifications@github.com>:

**Comment by superRaytin** [comment]
你目前遇到的问题应该与 paginationjs 无关，从代码看来可能是 jQuery 使用上有一些差错。

方便的话可以提供一个可重现的 demo: http://codepen.io/superRaytin/pen/VjZNJN?editors=0010

我可以帮你看看问题出在哪。

**Comment by RexChip** [comment]
demo 請您參考這個: http://codepen.io/Midorii/pen/WxNgNW
麻煩您了，謝謝。

**Comment by superRaytin** [comment]
模板方法输出为 Table 列表，不知道你要的是否这个？我 fork 了一个你的 demo，参考一下：http://codepen.io/superRaytin/pen/pboxYV?editors=1010

**Comment by RexChip** [comment]
是的，謝謝您，我繼續研究怎麼套用！非常感謝！
