### ISSUE TITLE
Can't set parameter 'pageNumber'?

### ISSUE THREAD

**Issue by sytana** [superRaytin/paginationjs#60]
![image](https://user-images.githubusercontent.com/11701135/39610959-70f20960-4f86-11e8-8987-c1fdceebe8fb.png)
------
![image](https://user-images.githubusercontent.com/11701135/39611041-02cc4652-4f87-11e8-9666-1e042a824394.png)
------
![image](https://user-images.githubusercontent.com/11701135/39611045-0d333fb0-4f87-11e8-86af-42ff3d977900.png)

**Comment by ntakim** [comment]
Can someone check this issue?

**Comment by sytana** [comment]
Who can help me? Thanks.

**Comment by fabiofdsantos** [comment]
@sytana,
Check this explanation: https://github.com/superRaytin/paginationjs/issues/44#issuecomment-359229843

**Comment by superRaytin** [comment]
@sytana in this case, you can call `container.pagination('go', 21)` in `callback` function
