### ISSUE TITLE
Not able to customize pagination (further)

### ISSUE THREAD

**Issue by insoluzioni** [superRaytin/paginationjs#62]
I suggest adding this to `generateHTML: function(args)`

`var aClassName = attributes.aClassName;`

And also add it to <a> tags when generating pagination. This offers more flexibility, for example, I did this to be able to use Bootstrap styling.

Thanks

**Comment by superRaytin** [comment]
You can just add `className: 'custom-paginationjs'` and then overwriting it by using the same css class such as `paginationjs-page`

**Comment by sp01109** [comment]
I think @insoluzioni was referring to `<a>` tag such as `<a href="' + pageLink + '" class="'+aClassName+'">`. It is required if someone is going to use bootstrap to styling the pagnitation.
