### ISSUE TITLE
pageNumber doesn't work when i fetch data from api

### ISSUE THREAD

**Issue by SergiOnGit** [superRaytin/paginationjs#63]
That must be fixed and this plugin will be the best JQuery pagination plugin!

**Comment by fabiofdsantos** [comment]
@SergiOnGit,
What do you mean by it doesn't works? Could you please provide an example?

**Comment by alemdc** [comment]
If he fetch data using ajax /json it doesnt give him the pagination. mine is showing all the records. It doesnt work sir.

**Comment by JesusADS** [comment]
Why is this closed? I'm having the same problem. The documentations says:

> By default, pageNumber and pageSize will be sent. 

but in practice is not true, i have this:

```
$.ajax({
    headers : {
        //CUSTOM HEADERS
    },
    method : 'GET',
    url: 'https://my/api/url',
    success: function(response) {
        done(response.data);
    }
});
```

and the request is to: `https://my/api/url` without any parameters, I need pageNumber and pageSize to be sent.
