### ISSUE TITLE
how to embed filter/search option

### ISSUE THREAD

**Issue by rakeshnayak360** [superRaytin/paginationjs#64]
i want to use search option for table. How can i achieve this using pagination.js??

**Comment by fabiofdsantos** [comment]
@rakeshnayak360,

Yes if you want to perform the search operation on the back-end side. You have to change dataSource URL dynamically depending on your current scenario.

**Comment by W3b3r** [comment]
Hi guys,

how can change or force recall of dataSource ajax if there is some search option active?

Thanks :D

**Comment by superRaytin** [comment]
guess this demo may help http://pagination.js.org/index.html#totalNumber_locator
