### ISSUE TITLE
Paginationjs not working

### ISSUE THREAD

**Issue by rajkumar14051988** [superRaytin/paginationjs#68]
We have referred your demo and tried it in our site, but we are getting the following error:

> Uncaught TypeError: Cannot read property 'hooks' of undefined

Kindly advice how to fix this issue.

**Comment by kevinyeo92** [comment]
I faced this issue when I spell the element id name wrongly.

Please check your element spelling

**Comment by SADRONU** [comment]
https://stackoverflow.com/questions/60290398/how-to-use-pagination-with-api-tmdb
I have the same problem.
