### ISSUE TITLE
hideWhenLessThanOnePage does not return callback when only one page

### ISSUE THREAD

**Issue by lostasia** [superRaytin/paginationjs#69]
If the dataSource array length is smaller than pageSize, and hideWhenLessThanOnePage is set true, callback function never returns data, means not only pagination hides, no data for you to show the first page as well.

Isn't it supposed to still return the first page data to be displayed?

**Comment by adrianmann** [comment]
@lostasia I am seeing this scenario also just a few moments ago even though I have looked at:

https://github.com/superRaytin/paginationjs/issues/47
https://github.com/superRaytin/paginationjs/issues/39
https://github.com/superRaytin/paginationjs/issues/33

 I will report back if I find anything else. Any help is appreciated.

**Comment by adrianmann** [comment]
https://github.com/superRaytin/paginationjs/blob/master/dist/pagination.js#L79?

Where does the render happen, especially if the code doesn't get to here after the `return` on line 79 above: https://github.com/superRaytin/paginationjs/blob/master/dist/pagination.js#L82 ?

Edit: I also just tried putting `hideWhenLessThanOnePage: true` after the `callback` and that didn't work either.

**Comment by superRaytin** [comment]
Fixed in `2.1.5`
