### ISSUE TITLE
如何获取下标index

### ISSUE THREAD

**Issue by bihaitian** [superRaytin/paginationjs#7]
# 使用中如果获取每个item在数组中对应的下标？  @superRaytin

**Comment by superRaytin** [comment]
你说的下标是不是指当前页码？

每一次发生分页，`callback` 中会有 `pagination` 信息：http://paginationjs.com/docs/index-cn.html#callback

也提供了手动获取当前页码的方法：http://paginationjs.com/docs/index-cn.html#getSelectedPageNum

**Comment by bihaitian** [comment]
你好，多谢你的回复，我解决了，根据当前页算下标，不过手动获取当前页码的调用方法该如何写？额，好几个方法我不知道该如何调用。  @/尴尬   @superRaytin

**Comment by superRaytin** [comment]
调用实例方法很简单，方法的调用方式都是一致的 `container.pagination(MethodName, Parameter)`。

比如手动跳转到第 8 页：

``` js
container.pagination('go', 8);
```

http://paginationjs.com/docs/index.html#go

**Comment by superRaytin** [comment]
多看看文档，基本上都有答案。
