### ISSUE TITLE
Is it possible to update data source?

### ISSUE THREAD

**Issue by kavaghela** [superRaytin/paginationjs#77]
I want to update/refresh/reload data source after generating list view. Is it possible?

**Comment by satyasaadhak** [comment]
Yes, please. I'm deleting some elements in the pagination list, but when you go to and different page and come back to where you deleted that element the element reappears since it's there in the datasource. Is there any fix to this?

**Comment by Defatul** [comment]
`
    function draw(){
        container.pagination('go', container.pagination('getSelectedPageNum'));
    }
`

**Comment by Defatul** [comment]
Ajax için

`function draw(){ container.pagination('go', container.pagination('getSelectedPageNum')); }`

**Comment by Defatul** [comment]
For ajax

`function draw(){ container.pagination('go', container.pagination('getSelectedPageNum')); }`
