### ISSUE TITLE
如何清空已经渲染在页面的数据？

### ISSUE THREAD

**Issue by bihaitian** [superRaytin/paginationjs#8]
动态把datasource清空了， 但是已经显示在页面的该如何清除？
那些reflesh和remove之类的方法如何调用？ @superRaytin  期待您的答复，特别感谢。

**Comment by bihaitian** [comment]
我找到了，是我看文档不仔细~~

**Comment by bihaitian** [comment]
还是没能解决呢，如果我清空了datasource，但是之前渲染的数据还存在页面上。 @superRaytin

**Comment by superRaytin** [comment]
`$('#your-data-container-selector').html('')` 清空一下界面就解决你的问题了吧。

**Comment by superRaytin** [comment]
这和分页组件无关，你也可以选择销毁分页实例：http://paginationjs.com/docs/index-cn.html#destroy 或者暂时隐藏 http://paginationjs.com/docs/index-cn.html#hide

**Comment by bihaitian** [comment]
其实我想到.html('')来解决问题了。只是觉得不太官方， 希望有个你封装好的方法可以调用，哈哈，我试了hide和destroy，是不一样的效果，谢谢你了，看来目前只能用.html()了。多谢！
