### ISSUE TITLE
Which property to set total number count to the pagination

### ISSUE THREAD

**Issue by purugopalan** [superRaytin/paginationjs#80]
I have used dataSource: function(done) { $.ajax({ method and called REST api (POST method not get), not sure how to set total number of records and the help states that total number available only if datasource option is URL. Since i need to call POST method URL datasource option not works as i have to go for datasource by using $,ajax.
Pls let me know the solution, how to set total number of records to the pagination request, so that pagination 2 or 3 etcc. page will be displayed in UI.. Currently only 1st page data being displayed.

**Comment by dtsellos03** [comment]
I tried this:
Use the URL option for datasource, and modify the default request:
```
  ajax: {
        beforeSend: function() {
            console.log(this) // this is the AJAX request parameters
            this.type = 'POST';
            this.url = 'http:///...';
            dataContainer.html('Loading data from flickr.com ...');
        }
    },
```

**Comment by superRaytin** [comment]
please check the docs: http://pagination.js.org/docs/index.html#dataSource
make sure `done(response)` has been called
