### ISSUE TITLE
服务器渲染时能否不指定datasource

### ISSUE THREAD

**Issue by avicha** [superRaytin/paginationjs#81]
我是使用服务器渲染列表数据的，但我只想使用paginationjs显示分页的逻辑，能够不指定datasource，只指定每页请求数/总数/当前页数么，我现在就是后台有多少条数据，datasource就设置为[1,2,3,...,...total_rows]，但是万一后台有万级的数据，这样子写内存就耗费了

**Comment by superRaytin** [comment]
数据量大的话，可以把 dataSource 指定为你的数据接口，同时指定 totalNumber
