### ISSUE TITLE
Why is the default styling not applied ?

### ISSUE THREAD

**Issue by Rmy5** [superRaytin/paginationjs#82]
Why is the default styling not applied ?

I installed the lib with `yarn add pagination.js`
And used it with: `require('paginationjs')`

![cap](https://user-images.githubusercontent.com/30668074/49768078-55a95c00-fcdb-11e8-8cd2-fc92cf08285f.png)

**Comment by barabulkit** [comment]
i actually had the same issue, its fixing by downloading [pagination.css](https://github.com/superRaytin/paginationjs/blob/master/dist/pagination.css) from dist of this repository and them adding this stylesheet to your page with link tag, then you can use className: 'paginationjs-theme-blue' and that will work.

**Comment by Brian-Jiang** [comment]
I have the same issue too

**Comment by jmlp1327** [comment]
@py-den Thank you very much 👍

**Comment by benmcm1994** [comment]
For those using webpack, importing the css from NPM like this `@import "~paginationjs/dist/pagination.css";` Worked for me :)
