### ISSUE TITLE
Make controls stay the same size when traversing

### ISSUE THREAD

**Issue by Bakuryu** [superRaytin/paginationjs#83]
Its rather annoying when you are traversing the pages and the controls move under your mouse. This is especially annoying for any users that use the arrow buttons because after the first few clicks they must re-adjust their mouse to continue clicking. Is this a common practice or what? Is there a way to fix this? Even with it centered this is still an issue.

**Comment by superRaytin** [comment]
set `pageRange: null` may help https://github.com/superRaytin/paginationjs/commit/8364d413d437262a7b28508f6edfbe3f9f5a67ee
