### ISSUE TITLE
ajax example

### ISSUE THREAD

**Issue by weiyuc** [superRaytin/paginationjs#9]
hai,
But try to understand I'am bad for English...

this is my code,

function pagination(idName, className, url) {
        var pageContainer = $(idName);
        var dataContainer = $(className);
        $.ajax({
            url: url,
            type: 'post',
            dataType: 'jsonp',
            jsonp: "callbackparam",
            jsonpCallback: "success_jsonpCallback",
            data: {
                'params': 'pageNumber=1&pageSize=2'
            },
            success: function(json) {
                pageContainer.pagination({
                    dataSource: json.data.rows,
                    totalNumber:json.data.total,
                    pageNumber:json.data.pageNumber,
                    pageSize:json.data.pageSize,
                    pageRange:2,
                    callback: function(data, pagination) {
                        console.log(pagination);
                    }
                });  
            }
        });
    }

now, json.data.total is 10,but totalNumber in console.log(pagination) is 2,

**Comment by superRaytin** [comment]
你可以用中文...

如果传入了 dataSource 并且是个数组，那 dataSource 的长度会赋给 totalNumber，并且不需要手动设置。

在异步中（即 dataSource 是个数据接口 url），这时候才需要手动设置 totalNumber。

**Comment by relaxyabc** [comment]
@superRaytin  请问下  ajax 的请求中是否可以支持 jQuery 动态取参数呢  V2.1.4  貌似不支持
``` js
$('#Pagination').pagination({
            dataSource: "myApi",
            locator: 'data',
            totalNumberLocator: function (res) {
                return res.totalCount;
            },
            alias: {
                pageNumber: 'pageIndex',
                pageSize: 'pageSize'
            },
            ajax: {
                data: {name:$('#name'),age:$('#age')}
            },
            callback: function (data, pagination) {
                data.forEach(function (item) {
                   var html = template(data);
                    dataContainer.html(html);
                })
            }
        })
````

就是 ajax 部分的   data 是否支持 jQuery 动态取参,
```js
ajax: {
     data: {name:$('#name'),age:$('#age')}
 },
```

已经解决了。
```js
ajax: function () {
                return {
                    data: {
                        input: $("#input").val(),
                        phone: $("#phone").val()
                    }
                }
            },
```
