### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hooks' of undefined

### ISSUE THREAD

**Issue by Danissss** [superRaytin/paginationjs#90]
Uncaught TypeError: Cannot read property 'hooks' of undefined

Do I miss some dependencies for using this js?

Thanks

**Comment by superRaytin** [comment]
Could you please provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Comment by AndreyGudin** [comment]
Same error. What can i do?
