### ISSUE TITLE
Go top after click on page

### ISSUE THREAD

**Issue by Lowell130** [superRaytin/paginationjs#93]
Hello
after click on the page button, how i can move to top page?

**Comment by superRaytin** [comment]
If you want to move to the first page, you can just call `container.pagination('go', 8)` or `container.pagination(8)`

ref: http://pagination.js.org/docs/index.html#go

**Comment by danielbenjamins** [comment]
I think @Lowell130 meant he wants to get automatically scrolled to the top of the container. So when you click on 2, 3, etc. you start seeing the first results of the new page instead of it keeps you hanging at the bottom of the container (where the pagination is).

**Comment by npujar** [comment]
afterRender: function() {
    $('html').animate({
          scrollTop: ($("body").offset().top)
     }, 150);
}

@Lowell130 @eaglejohn  : I used the afterRender method to manually trigger scroll to top

**Comment by npujar** [comment]
```
afterRender: function() {
    $('html').animate({
          scrollTop: ($("body").offset().top)
     }, 150);
}
```

@Lowell130  @eaglejohn  : I used the afterRender method to manually trigger scroll to top
