### ISSUE TITLE
Error cannot work on jquery ajax

### ISSUE THREAD

**Issue by DEVfancybear** [superRaytin/paginationjs#97]
I tried calling data on ajax to paginate but it didn't work, looking forward to your help
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <ul id="users"></ul>
    <div id="pagination-container"></div>
  </body>
  <script src="./pagination.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
    let request = new XMLHttpRequest();
    request.open("GET", "https://data-aq-mobile.herokuapp.com/products", true);
    request.onload = function() {
      // Convert JSON data to an object
      let users = JSON.parse(this.response);
      let output = "";
      for (var i = 0; i < users.length; i++) {
        output +=
          "<li>" + users[i].name + " is " + users[i].vitri + " years old.";
        ("</li>");
      }
      document.getElementById("users").innerHTML = output;
      console.log(users);
    };
    request.send();
    paginator = () =>
      $("#users").pagination({
        showGoInput: true,
        showGoButton: true,
        dataSource: done =>
          $.ajax({
            url: "https://data-aq-mobile.herokuapp.com/products?pageNum=2&limit=10",
            success: data => {
              done(data.content.map((e, i) => i));
            }
          })
      });
  </script>
</html>

**Comment by 3rc4n** [comment]
Add the script tag for loading jquery before '<script src="./pagination.js"></script>'

**Comment by superRaytin** [comment]
Could you please provide a re-produciable demo: http://codepen.io/superRaytin/pen/RRoZBz

**Comment by DEVfancybear** [comment]
yes I have a solution for it, here is my source code: https://github.com/DEVfancybear/pug-ajax-juery-demo
